// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useradminloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptretrieveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptretrievetreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}
