// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useradminloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptretrieveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptretrievetreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommondeptupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _kvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonkvcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonkvdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonkvretrieveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonkvupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonpostcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonpostdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonpostretrieveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonpostupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonrolecreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonroledeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonroleretrieveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usercommonroleupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}
