// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/common/hlog"
	gatewaycmd "github.com/wheelergeo/g-otter-gateway/cmd"
)

func main() {
	err := gatewaycmd.Command().Execute()
	if err != nil {
		hlog.Fatal(err)
	}
}
