// Code generated by hertz generator.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userverifyMw() []app.HandlerFunc {
	// your code...
	return nil
}
